/**
 * Header menu items: Navigation, Manual Controls, Modes.
 */
import type { HeaderMenuProps, MenuItemConfig } from "./headerMenuConfigTypes";

export function getNavControlsModesItems(
  props: HeaderMenuProps,
  c: (fn: () => void) => () => void,
  navigate: (path: string) => void,
  showTimer: boolean,
): MenuItemConfig[] {
  return [
    {
      id: "home",
      section: "settings",
      visible: true,
      label: "Home",
      sortKey: "Home",
      title: "Return to main menu",
      onClick: c(() => navigate("/")),
      subMenu: "navigation",
    },
    {
      id: "new",
      section: "settings",
      visible: true,
      label: "New puzzle",
      sortKey: "New puzzle",
      title: "Start a fresh puzzle",
      onClick: c(props.onNewPuzzle),
      subMenu: "navigation",
    },
    {
      id: "undo",
      section: "settings",
      visible: !!props.onUndo,
      label: "Undo",
      sortKey: "Undo",
      title: "Revert last piece placement",
      onClick: c(props.onUndo ?? (() => {})),
      subMenu: "manualControls",
      disabled: !props.canUndo,
      disabledTitle: !props.canUndo ? "No moves to undo" : undefined,
    },
    {
      id: "redo",
      section: "settings",
      visible: !!props.onRedo,
      label: "Redo",
      sortKey: "Redo",
      title: "Reapply last undone move",
      onClick: c(props.onRedo ?? (() => {})),
      subMenu: "manualControls",
      disabled: !props.canRedo,
      disabledTitle: !props.canRedo ? "No moves to redo" : undefined,
    },
    {
      id: "resetView",
      section: "settings",
      visible: !!props.onResetView,
      label: "Reset View",
      sortKey: "Reset View",
      title: "Reset zoom and pan to center the board",
      onClick: c(props.onResetView ?? (() => {})),
      subMenu: "manualControls",
    },
    {
      id: "zoomIn",
      section: "settings",
      visible: true,
      label: "Zoom In",
      sortKey: "Zoom In",
      title: "Zoom in on the board",
      onClick: c(props.onZoomIn ?? (() => {})),
      subMenu: "manualControls",
    },
    {
      id: "zoomOut",
      section: "settings",
      visible: true,
      label: "Zoom Out",
      sortKey: "Zoom Out",
      title: "Zoom out to see more of the board",
      onClick: c(props.onZoomOut ?? (() => {})),
      subMenu: "manualControls",
    },
    {
      id: "deliberateDetach",
      section: "settings",
      visible: !!props.onToggleDeliberateDetach,
      label: "Deliberate Detach",
      sortKey: "Deliberate Detach",
      title: "Require hold or shake to detach placed pieces",
      ariaLabel: props.deliberateDetachEnabled
        ? "Deliberate detach on"
        : "Deliberate detach off",
      onClick: c(props.onToggleDeliberateDetach ?? (() => {})),
      subMenu: "modes",
      isToggle: true,
      checked: !!props.deliberateDetachEnabled,
    },
    {
      id: "lock",
      section: "settings",
      visible: true,
      label: "Tap to Rotate",
      sortKey: "Tap to Rotate",
      title: "Tap a piece in the tray to rotate it",
      onClick: c(props.onTogglePieceLocking),
      subMenu: "modes",
      isToggle: true,
      checked: props.pieceLockingEnabled,
    },
    {
      id: "autoRotateOnSnap",
      section: "settings",
      visible: true,
      label: "Auto-align on snap",
      sortKey: "Auto-align on snap",
      title:
        "When on, pieces snap to correct rotation when placed next to another. When off, you must rotate them yourself.",
      onClick: c(props.onToggleAutoRotateOnSnap ?? (() => {})),
      subMenu: "modes",
      isToggle: true,
      checked: props.autoRotateOnSnap !== false,
    },
    {
      id: "relaxedMode",
      section: "settings",
      visible: !!props.onToggleRelaxedMode,
      label: "Relaxed Mode",
      sortKey: "Relaxed Mode",
      title: "Hide timer and take your time",
      ariaLabel: props.relaxedModeEnabled ? "Relaxed Mode on" : "Relaxed Mode off",
      onClick: c(props.onToggleRelaxedMode ?? (() => {})),
      subMenu: "modes",
      isToggle: true,
      checked: !!props.relaxedModeEnabled,
    },
    {
      id: "driftMode",
      section: "settings",
      visible: !!props.onToggleDriftMode,
      label: "Drift Mode",
      sortKey: "Drift Mode",
      title: "Pieces drift slightly for organic feel",
      ariaLabel: props.driftModeEnabled ? "Drift Mode on" : "Drift Mode off",
      onClick: c(props.onToggleDriftMode ?? (() => {})),
      subMenu: "modes",
      isToggle: true,
      checked: !!props.driftModeEnabled,
    },
    {
      id: "showTimer",
      section: "settings",
      visible: true,
      label: "Show Timer",
      sortKey: "Show Timer",
      title: "Show or hide elapsed time",
      onClick: c(() => props.setTimeMode(showTimer ? "relaxed" : "elapsed")),
      subMenu: "modes",
      isToggle: true,
      checked: showTimer,
    },
    {
      id: "zenMode",
      section: "settings",
      visible: true,
      label: "Zen Ambient",
      sortKey: "Zen Ambient",
      title: "No timer or rankings; subtle ambient background and soft transitions",
      onClick: c(props.onToggleZenMode ?? (() => {})),
      subMenu: "modes",
      isToggle: true,
      checked: !!props.zenModeEnabled,
    },
    {
      id: "mysteryMode",
      section: "settings",
      visible: true,
      label: "Mystery Mode",
      sortKey: "Mystery Mode",
      title: "Hide reference image; reveal sections only after correct placements",
      onClick: c(props.onToggleMysteryMode ?? (() => {})),
      subMenu: "modes",
      isToggle: true,
      checked: !!props.mysteryModeEnabled,
    },
    {
      id: "precisionMode",
      section: "settings",
      visible: true,
      label: "Precision Mode",
      sortKey: "Precision Mode",
      title: "Score snap accuracy; higher precision earns bonus ranking points",
      onClick: c(props.onTogglePrecisionMode ?? (() => {})),
      subMenu: "modes",
      isToggle: true,
      checked: !!props.precisionModeEnabled,
    },
    {
      id: "dynamicDifficulty",
      section: "settings",
      visible: true,
      label: "Dynamic Difficulty",
      sortKey: "Dynamic Difficulty",
      title: "Puzzle adapts tolerance and complexity from your skill history",
      onClick: c(props.onToggleDynamicDifficulty ?? (() => {})),
      subMenu: "modes",
      isToggle: true,
      checked: !!props.dynamicDifficultyEnabled,
    },
    {
      id: "adaptivePersonality",
      section: "settings",
      visible: true,
      label: "Adaptive Personality",
      sortKey: "Adaptive Personality",
      title: "UI tone adapts to your pace (fast = competitive, slow = calm)",
      onClick: c(props.onToggleAdaptivePersonality ?? (() => {})),
      subMenu: "modes",
      isToggle: true,
      checked: !!props.adaptivePersonalityEnabled,
    },
  ];
}
