/**
 * Header menu items: Navigation, Manual Controls, Modes.
 */
import type { HeaderMenuProps, MenuItemConfig } from "./headerMenuConfigTypes";

export function getNavControlsModesItems(
  props: HeaderMenuProps,
  c: (fn: () => void) => () => void,
  navigate: (path: string) => void,
  showTimer: boolean,
): MenuItemConfig[] {
  return [
    {
      id: "home",
      section: "settings",
      visible: true,
      label: "Home",
      sortKey: "Home",
      title: "Return to main menu",
      onClick: c(() => navigate("/")),
      subMenu: "navigation",
    },
    {
      id: "new",
      section: "settings",
      visible: true,
      label: "New puzzle",
      sortKey: "New puzzle",
      title: "Start a fresh puzzle",
      onClick: c(props.onNewPuzzle),
      subMenu: "navigation",
    },
    {
      id: "undo",
      section: "settings",
      visible: !!props.onUndo,
      label: "Undo",
      sortKey: "0 Undo",
      title: "Revert last piece placement",
      onClick: c(props.onUndo ?? (() => {})),
      subMenu: "manualControls",
      disabled: !props.canUndo,
      disabledTitle: !props.canUndo ? "No moves to undo" : undefined,
    },
    {
      id: "redo",
      section: "settings",
      visible: !!props.onRedo,
      label: "Redo",
      sortKey: "1 Redo",
      title: "Reapply last undone move",
      onClick: c(props.onRedo ?? (() => {})),
      subMenu: "manualControls",
      disabled: !props.canRedo,
      disabledTitle: !props.canRedo ? "No moves to redo" : undefined,
    },
    {
      id: "resetView",
      section: "settings",
      visible: !!props.onResetView,
      label: "Reset View",
      sortKey: "2 Reset View",
      title: "Reset zoom and pan to center the board",
      onClick: c(props.onResetView ?? (() => {})),
      subMenu: "manualControls",
    },
    {
      id: "zoomIn",
      section: "settings",
      visible: true,
      label: "Zoom In",
      sortKey: "3 Zoom In",
      title: "Zoom in on the board",
      onClick: c(props.onZoomIn ?? (() => {})),
      subMenu: "manualControls",
    },
    {
      id: "zoomOut",
      section: "settings",
      visible: true,
      label: "Zoom Out",
      sortKey: "4 Zoom Out",
      title: "Zoom out to see more of the board",
      onClick: c(props.onZoomOut ?? (() => {})),
      subMenu: "manualControls",
    },
    {
      id: "deliberateDetach",
      section: "settings",
      visible: !!props.onToggleDeliberateDetach,
      label: "Deliberate Detach",
      sortKey: "0 Deliberate Detach",
      title: "Require hold or shake to detach placed pieces",
      ariaLabel: props.deliberateDetachEnabled
        ? "Deliberate detach on"
        : "Deliberate detach off",
      onClick: c(props.onToggleDeliberateDetach ?? (() => {})),
      subMenu: "modes",
      isToggle: true,
      checked: !!props.deliberateDetachEnabled,
    },
    {
      id: "lock",
      section: "settings",
      visible: true,
      label: "Tap to Rotate",
      sortKey: "1 Tap to Rotate",
      title: "Tap a piece in the tray to rotate it",
      onClick: c(props.onTogglePieceLocking),
      subMenu: "modes",
      isToggle: true,
      checked: props.pieceLockingEnabled,
    },
    {
      id: "relaxedMode",
      section: "settings",
      visible: !!props.onToggleRelaxedMode,
      label: "Relaxed Mode",
      sortKey: "2 Relaxed Mode",
      title: "Hide timer and take your time",
      ariaLabel: props.relaxedModeEnabled ? "Relaxed Mode on" : "Relaxed Mode off",
      onClick: c(props.onToggleRelaxedMode ?? (() => {})),
      subMenu: "modes",
      isToggle: true,
      checked: !!props.relaxedModeEnabled,
    },
    {
      id: "driftMode",
      section: "settings",
      visible: !!props.onToggleDriftMode,
      label: "Drift Mode",
      sortKey: "3 Drift Mode",
      title: "Pieces drift slightly for organic feel",
      ariaLabel: props.driftModeEnabled ? "Drift Mode on" : "Drift Mode off",
      onClick: c(props.onToggleDriftMode ?? (() => {})),
      subMenu: "modes",
      isToggle: true,
      checked: !!props.driftModeEnabled,
    },
    {
      id: "showTimer",
      section: "settings",
      visible: true,
      label: "Show Timer",
      sortKey: "4 Show Timer",
      title: "Show or hide elapsed time",
      onClick: c(() => props.setTimeMode(showTimer ? "relaxed" : "elapsed")),
      subMenu: "modes",
      isToggle: true,
      checked: showTimer,
    },
  ];
}
