/**
 * Header menu items: Display, Effects, Assistance, Piece Shape, Audio, Advanced, Stats, Share, About, Help.
 */
import type { HeaderMenuProps, MenuItemConfig } from "./headerMenuConfigTypes";

const GITHUB_REPO_URL = "https://github.com/NickTheDevOpsGuy/phuzzle";
const GITHUB_CONTRIBUTORS_URL =
  "https://github.com/NickTheDevOpsGuy/phuzzle/blob/develop/CONTRIBUTORS.md";

export function getDisplayAudioAdvancedItems(
  props: HeaderMenuProps,
  c: (fn: () => void) => () => void,
  navigate: (path: string) => void,
): MenuItemConfig[] {
  return [
    {
      id: "showPreview",
      section: "settings",
      visible: true,
      label: "Preview",
      sortKey: "0 Preview",
      title: "Show reference image while solving",
      onClick: c(props.onTogglePreview),
      subMenu: "display",
      isToggle: true,
      checked: props.showPreview,
    },
    {
      id: "modifierNone",
      section: "settings",
      visible: !!props.onDailyPreferredModifierChange,
      label: "None",
      sortKey: "0 None",
      title: "No visual modifier",
      onClick: c(() => props.onDailyPreferredModifierChange?.("none")),
      subMenu: "effects",
      isToggle: true,
      checked: (props.dailyPreferredModifier ?? "none") === "none",
      ariaLabel: "None – no visual modifier",
    },
    {
      id: "modifierFog",
      section: "settings",
      visible: !!props.onDailyPreferredModifierChange,
      label: "Fog",
      sortKey: "1 Fog",
      title: "Reduced contrast until piece is placed",
      onClick: c(() => props.onDailyPreferredModifierChange?.("fog")),
      subMenu: "effects",
      isToggle: true,
      checked: props.dailyPreferredModifier === "fog",
      ariaLabel: "Fog – reduced contrast until placed",
    },
    {
      id: "modifierNight",
      section: "settings",
      visible: !!props.onDailyPreferredModifierChange,
      label: "Night",
      sortKey: "2 Night",
      title: "Dark palette with vignette",
      onClick: c(() => props.onDailyPreferredModifierChange?.("night")),
      subMenu: "effects",
      isToggle: true,
      checked: props.dailyPreferredModifier === "night",
      ariaLabel: "Night – dark palette and vignette",
    },
    {
      id: "modifierSepia",
      section: "settings",
      visible: !!props.onDailyPreferredModifierChange,
      label: "Sepia",
      sortKey: "3 Sepia",
      title: "Vintage sepia tone",
      onClick: c(() => props.onDailyPreferredModifierChange?.("sepia")),
      subMenu: "effects",
      isToggle: true,
      checked: props.dailyPreferredModifier === "sepia",
      ariaLabel: "Sepia – vintage tone",
    },
    {
      id: "alignmentGrid",
      section: "settings",
      visible: true,
      label: "Alignment Grid",
      sortKey: "Alignment Grid",
      title: "Show grid lines to help align pieces",
      onClick: c(props.onToggleAlignmentGrid),
      subMenu: "assistance",
      isToggle: true,
      checked: props.showAlignmentGrid,
    },
    {
      id: "edgeHighlight",
      section: "settings",
      visible: true,
      label: "Edge Highlight",
      sortKey: "Edge Highlight",
      title: "Highlight edge pieces in the tray",
      onClick: c(props.onToggleEdgeHighlight),
      subMenu: "assistance",
      isToggle: true,
      checked: props.showEdgeHighlight,
    },
    {
      id: "clusterOutline",
      section: "settings",
      visible: !!props.onToggleClusterOutline,
      label: "Cluster Outlines",
      sortKey: "Cluster Outlines",
      title: "Show outlines around completed clusters",
      ariaLabel: props.showClusterOutline
        ? "Cluster outlines on"
        : "Cluster outlines off",
      onClick: c(props.onToggleClusterOutline ?? (() => {})),
      subMenu: "assistance",
      isToggle: true,
      checked: !!props.showClusterOutline,
    },
    {
      id: "ghostHint",
      section: "settings",
      visible: true,
      label: "Ghost Hint",
      sortKey: "Ghost Hint",
      title: "Show ghost placement when dragging a piece",
      onClick: c(props.onToggleGhostHint),
      subMenu: "assistance",
      isToggle: true,
      checked: props.showGhostHint,
    },
    {
      id: "ghostWhenIdle",
      section: "settings",
      visible: true,
      label: "Ghost When Idle",
      sortKey: "Ghost When Idle",
      title: "Show ghost after a moment of idleness",
      onClick: c(props.onToggleGhostWhenIdle),
      subMenu: "assistance",
      isToggle: true,
      checked: props.showGhostWhenIdle,
    },
    {
      id: "immersiveMode",
      section: "settings",
      visible: true,
      label: "Immersive Mode",
      sortKey: "Immersive Mode",
      title: "Hide UI until you hover or tap the edge",
      onClick: c(props.onToggleImmersiveMode),
      subMenu: "display",
      isToggle: true,
      checked: props.immersiveMode,
    },
    {
      id: "progressiveReveal",
      section: "settings",
      visible: true,
      label: "Progressive Reveal",
      sortKey: "Progressive Reveal",
      title: "Reveal reference image as you place pieces",
      onClick: c(props.onToggleProgressiveReveal ?? (() => {})),
      subMenu: "assistance",
      isToggle: true,
      checked: !!props.progressiveRevealMode,
    },
    {
      id: "pieceCutClassic",
      section: "settings",
      visible: !!props.onPieceCutTypeChange,
      label: "Classic",
      sortKey: "0 Piece shape Classic",
      title: "Classic jigsaw cuts – applies to next puzzle",
      onClick: c(() => props.onPieceCutTypeChange?.("classic")),
      subMenu: "pieceShape",
      radioSelected: (props.pieceCutType ?? "classic") === "classic",
      ariaLabel: "Classic – applies to next puzzle",
    },
    {
      id: "pieceCutIrregular",
      section: "settings",
      visible: !!props.onPieceCutTypeChange,
      label: "Irregular",
      sortKey: "1 Piece shape Irregular",
      title: "Irregular wavy cuts – applies to next puzzle",
      onClick: c(() => props.onPieceCutTypeChange?.("irregular")),
      subMenu: "pieceShape",
      radioSelected: (props.pieceCutType ?? "classic") === "irregular",
      ariaLabel: "Irregular – applies to next puzzle",
    },
    {
      id: "pieceCutHard",
      section: "settings",
      visible: !!props.onPieceCutTypeChange,
      label: "Hard",
      sortKey: "2 Piece shape Hard",
      title: "Hard uniform cuts – applies to next puzzle",
      onClick: c(() => props.onPieceCutTypeChange?.("hard")),
      subMenu: "pieceShape",
      radioSelected: (props.pieceCutType ?? "classic") === "hard",
      ariaLabel: "Hard – applies to next puzzle",
    },
    {
      id: "haptics",
      section: "settings",
      visible: props.canShowHaptics,
      label: "Haptics",
      sortKey: "Haptics",
      title: "Vibration feedback on snap and actions",
      onClick: c(props.onToggleHaptics),
      subMenu: "audio",
      isToggle: true,
      checked: props.hapticsEnabled,
    },
    {
      id: "sound",
      section: "settings",
      visible: true,
      label: "Sound Effects",
      sortKey: "Sound Effects",
      title: "Play sounds when placing and snapping pieces",
      onClick: c(props.onToggleSound),
      subMenu: "audio",
      isToggle: true,
      checked: props.soundEnabled,
    },
    {
      id: "music",
      section: "settings",
      visible: !!props.onToggleMusic,
      label: "Background Music",
      sortKey: "Background Music",
      title: "Theme-based ambient music",
      ariaLabel: props.musicEnabled ? "Background music on" : "Background music off",
      onClick: c(props.onToggleMusic ?? (() => {})),
      subMenu: "audio",
      isToggle: true,
      checked: !!props.musicEnabled,
    },
    {
      id: "clearCache",
      section: "settings",
      visible: !!props.onClearCache,
      label: "Clear Cache",
      sortKey: "Clear Cache",
      title: "Clear cached puzzle images and data",
      onClick: c(props.onClearCache ?? (() => {})),
      subMenu: "advanced",
    },
    {
      id: "perfOverlay",
      section: "settings",
      visible: props.canShowDebug,
      label: "Performance Overlay",
      sortKey: "Performance Overlay",
      title: "Show FPS and draw call stats",
      onClick: c(props.onTogglePerfOverlay),
      subMenu: "advanced",
      isToggle: true,
      checked: props.debug.showPerfOverlay,
    },
    {
      id: "resetStats",
      section: "settings",
      visible: !!props.onResetStats,
      label: "Reset Local Stats",
      sortKey: "Reset Local Stats",
      title: "Clear all local best times – cannot be undone",
      onClick: c(props.onResetStats ?? (() => {})),
      subMenu: "advanced",
    },
    {
      id: "stats",
      section: "settings",
      visible: true,
      label: "Leaderboards",
      sortKey: "Leaderboards",
      title: "View daily and best-time leaderboards",
      onClick: c(() => navigate("/stats")),
      subMenu: "stats",
    },
    {
      id: "share",
      section: "settings",
      visible: !!props.onSharePuzzle,
      label: "Play with friend",
      sortKey: "Play with friend",
      title: "Start a co-op session to solve together",
      disabled: props.shareDisabled,
      disabledTitle: props.shareDisabled ? "Creating session…" : undefined,
      onClick: c(props.onSharePuzzle ?? (() => {})),
      subMenu: "share",
    },
    {
      id: "repo",
      section: "contribute",
      visible: true,
      label: "Get Involved",
      sortKey: "Get Involved",
      title: "Contribute on GitHub",
      onClick: c(() => window.open(GITHUB_REPO_URL, "_blank", "noopener,noreferrer")),
      subMenu: "contribute",
    },
    {
      id: "contributors",
      section: "contribute",
      visible: true,
      label: "Meet the Team",
      sortKey: "Meet the Team",
      title: "View contributors",
      onClick: c(() =>
        window.open(GITHUB_CONTRIBUTORS_URL, "_blank", "noopener,noreferrer"),
      ),
      subMenu: "contribute",
    },
    {
      id: "howToPlay",
      section: "help",
      visible: true,
      label: "How to Play",
      sortKey: "How to Play",
      title: "Learn the basics",
      onClick: c(props.onShowHowToPlay),
      subMenu: "help",
    },
    {
      id: "shortcuts",
      section: "help",
      visible: true,
      label: "Keyboard & Controls",
      sortKey: "Keyboard & Controls",
      title: "View keyboard shortcuts",
      onClick: c(props.onShowShortcuts),
      subMenu: "help",
    },
  ];
}
