/**
 * Build top bar props for play screen from layout context. Split out to keep playScreenSceneLayout under 300 lines.
 */
import { usePlayScreenTopBarProps } from "@/screens/Play/hooks/topBar/usePlayScreenTopBarProps";
import { SHOW_DEBUG } from "@/screens/Play/core/utils/playScreenUtils";

// eslint-disable-next-line @typescript-eslint/no-explicit-any -- ctx shape is large and shared
export function usePlayScreenTopBarPropsFromCtx(ctx: any) {
  const { setup, behavior, interactions } = ctx;
  const {
    ui,
    scene,
    timeMode,
    setTimeMode,
    countdownMinutes,
    setCountdownMinutes,
    grid,
  } = setup;
  const {
    manager,
    state,
    setState,
    puzzleKey: _puzzleKey,
    boardRef: _boardRef,
    elapsedSeconds: _elapsedSeconds,
    snapCombo: _snapCombo,
    announcerLine: _announcerLine,
    imgRef: _imgRef,
  } = behavior;
  const {
    displayElapsedSeconds,
    left,
    total,
    isComplete,
    dailyVisualModifier: _dailyVisualModifier,
    fogStrength: _fogStrength,
    immersive,
    bestTimeSeconds,
    handleSharePuzzle,
    handleNewGame: _handleNewGame,
    puzzleShareUrl: _puzzleShareUrl,
    share: _share,
    handleTrayPieceClick: _handleTrayPieceClick,
  } = interactions;
  const { sessionResult } = setup;

  return usePlayScreenTopBarProps({
    theme: scene.theme,
    setTheme: scene.setTheme,
    timeMode,
    setTimeMode,
    countdownMinutes,
    setCountdownMinutes,
    showPreview: ui.showPreview,
    setShowPreview: ui.setShowPreview,
    soundEnabled: ui.soundEnabled,
    musicEnabled: ui.musicEnabled,
    hapticsEnabled: ui.hapticsEnabled,
    pieceLockingEnabled: ui.pieceLockingEnabled,
    setPieceLockingEnabled: ui.setPieceLockingEnabled,
    magneticSnapEnabled: ui.magneticSnapEnabled,
    setMagneticSnapEnabled: ui.setMagneticSnapEnabled,
    snapGlowEnabled: ui.snapGlowEnabled,
    setSnapGlowEnabled: ui.setSnapGlowEnabled,
    autoRotateOnSnap: ui.autoRotateOnSnap,
    setAutoRotateOnSnap: ui.setAutoRotateOnSnap,
    showGhostHint: ui.showGhostHint,
    setShowGhostHint: ui.setShowGhostHint,
    showGhostWhenIdle: ui.showGhostWhenIdle,
    showEdgeHighlight: ui.showEdgeHighlight,
    showClusterOutline: ui.showClusterOutline,
    deliberateDetachEnabled: ui.deliberateDetachEnabled,
    showAlignmentGrid: ui.showAlignmentGrid,
    setShowAlignmentGrid: ui.setShowAlignmentGrid,
    toggleRelaxedMode: ui.toggleRelaxedMode,
    toggleDriftMode: ui.toggleDriftMode,
    toggleShowClusterOutline: ui.toggleShowClusterOutline,
    toggleDeliberateDetach: ui.toggleDeliberateDetach,
    toggleShowGhostWhenIdle: ui.toggleShowGhostWhenIdle,
    toggleShowEdgeHighlight: ui.toggleShowEdgeHighlight,
    toggleSound: ui.toggleSound,
    toggleMusic: ui.toggleMusic,
    toggleHaptics: ui.toggleHaptics,
    toggleFullscreen: ui.toggleFullscreen,
    toggleDebug: ui.toggleDebug,
    togglePerfOverlay: ui.togglePerfOverlay,
    toggleShowSilhouette: ui.toggleShowSilhouette,
    isFullscreen: ui.isFullscreen,
    isCoarsePointer: scene.isCoarsePointer,
    showDebug: SHOW_DEBUG,
    debug: ui.debug,
    setShowNewGameModal: ui.setShowNewGameModal,
    onStartThisPuzzleOver: scene.startThisPuzzleOver,
    setShowShortcuts: ui.setShowShortcuts,
    setShowHowToPlay: ui.setShowHowToPlay,
    setShowThemeModal: ui.setShowThemeModal,
    setShowResetStatsConfirm: scene.setShowResetStatsConfirm,
    setShowClearCacheConfirm: scene.setShowClearCacheConfirm,
    manager,
    state,
    setState,
    isPaused: ui.isPaused,
    setIsPaused: ui.setIsPaused,
    playUndo: ctx.soundPlay,
    undoCountRef: scene.undoCountRef,
    undoSnapBackRef: interactions.undoSnapBackRef,
    viewport: scene.viewport,
    relaxedModeEnabled: ui.relaxedModeEnabled,
    driftModeEnabled: ui.driftModeEnabled,
    immersiveMode: ui.immersiveMode,
    handleToggleImmersiveMode: immersive.handleToggleImmersiveMode,
    progressiveRevealMode: ui.progressiveRevealMode,
    setProgressiveRevealMode: ui.setProgressiveRevealMode,
    pieceCutType: ui.pieceCutType,
    setPieceCutType: ui.setPieceCutType,
    handleSharePuzzle,
    creatingSession: setup.creatingSession,
    dailyPreferredModifier: ui.dailyPreferredModifier,
    setDailyPreferredModifier: ui.setDailyPreferredModifier,
    snapToleranceOverride: ui.snapToleranceOverride,
    setSnapToleranceOverride: ui.setSnapToleranceOverride,
    elapsedSeconds: displayElapsedSeconds,
    piecesLeft: left,
    totalPieces: total,
    isComplete,
    grid,
    quadrantTimes: scene.quadrantTimes,
    bestTimeSeconds,
    lives: scene.lives,
    sessionId: setup.sessionId,
    realtimeStatus: setup.realtimeStatus,
    connectedCount: sessionResult.connectedCount,
    showImmersiveUi: immersive.showImmersiveUi,
    scheduleImmersiveHide: immersive.scheduleImmersiveHide,
    zenModeEnabled: ui.zenModeEnabled,
    mysteryModeEnabled: ui.mysteryModeEnabled,
    precisionModeEnabled: ui.precisionModeEnabled,
    dynamicDifficultyEnabled: ui.dynamicDifficultyEnabled,
    adaptivePersonalityEnabled: ui.adaptivePersonalityEnabled,
    toggleZenMode: ui.toggleZenMode,
    toggleMysteryMode: ui.toggleMysteryMode,
    togglePrecisionMode: ui.togglePrecisionMode,
    toggleDynamicDifficulty: ui.toggleDynamicDifficulty,
    toggleAdaptivePersonality: ui.toggleAdaptivePersonality,
    minimapVisible: ui.minimapVisible,
    toggleMinimap: ui.toggleMinimap,
  });
}
