/**
 * Header menu items: Display, Effects, Assistance, Piece Shape.
 */
import type {
  HeaderMenuProps,
  MenuItemConfig,
} from "@/screens/Play/components/headerMenu/headerMenuConfigTypes";

export function getDisplayItems(
  props: HeaderMenuProps,
  c: (fn: () => void) => () => void,
): MenuItemConfig[] {
  return [
    {
      id: "colorblindFriendly",
      section: "settings",
      visible: true,
      label: "Color blind friendly",
      sortKey: "Color blind friendly",
      title: "Use blue for progress and done states (easier for red–green color vision)",
      onClick: c(props.onToggleColorBlindFriendly ?? (() => {})),
      subMenu: "display",
      isToggle: true,
      checked: props.colorblindFriendly ?? false,
    },
    {
      id: "showPreview",
      section: "settings",
      visible: true,
      label: "Preview",
      sortKey: "Preview",
      title: "Show reference image while solving",
      onClick: c(props.onTogglePreview),
      subMenu: "display",
      isToggle: true,
      checked: props.showPreview,
    },
    {
      id: "showMinimap",
      section: "settings",
      visible: typeof props.minimapVisible === "boolean",
      label: "Show minimap",
      sortKey: "Show minimap",
      title: "Show board overview (25+ pieces); tap to pan",
      onClick: c(props.onToggleMinimap ?? (() => {})),
      subMenu: "display",
      isToggle: true,
      checked: props.minimapVisible ?? true,
    },
    {
      id: "modifierNone",
      section: "settings",
      visible: !!props.onDailyPreferredModifierChange,
      label: "None",
      sortKey: "None",
      title: "No visual modifier",
      onClick: c(() => props.onDailyPreferredModifierChange?.("none")),
      subMenu: "effects",
      isToggle: true,
      checked: (props.dailyPreferredModifier ?? "none") === "none",
      ariaLabel: "None – no visual modifier",
    },
    {
      id: "modifierFog",
      section: "settings",
      visible: !!props.onDailyPreferredModifierChange,
      label: "Fog",
      sortKey: "Fog",
      title: "Reduced contrast until piece is placed",
      onClick: c(() => props.onDailyPreferredModifierChange?.("fog")),
      subMenu: "effects",
      isToggle: true,
      checked: props.dailyPreferredModifier === "fog",
      ariaLabel: "Fog – reduced contrast until placed",
    },
    {
      id: "modifierNight",
      section: "settings",
      visible: !!props.onDailyPreferredModifierChange,
      label: "Night",
      sortKey: "Night",
      title: "Dark palette with vignette",
      onClick: c(() => props.onDailyPreferredModifierChange?.("night")),
      subMenu: "effects",
      isToggle: true,
      checked: props.dailyPreferredModifier === "night",
      ariaLabel: "Night – dark palette and vignette",
    },
    {
      id: "modifierSepia",
      section: "settings",
      visible: !!props.onDailyPreferredModifierChange,
      label: "Sepia",
      sortKey: "Sepia",
      title: "Vintage sepia tone",
      onClick: c(() => props.onDailyPreferredModifierChange?.("sepia")),
      subMenu: "effects",
      isToggle: true,
      checked: props.dailyPreferredModifier === "sepia",
      ariaLabel: "Sepia – vintage tone",
    },
    {
      id: "alignmentGrid",
      section: "settings",
      visible: true,
      label: "Alignment Grid",
      sortKey: "Alignment Grid",
      title: "Show grid lines to help align pieces",
      onClick: c(props.onToggleAlignmentGrid),
      subMenu: "assistance",
      isToggle: true,
      checked: props.showAlignmentGrid,
    },
    {
      id: "edgeHighlight",
      section: "settings",
      visible: true,
      label: "Edge Highlight",
      sortKey: "Edge Highlight",
      title: "Highlight edge pieces in the tray",
      onClick: c(props.onToggleEdgeHighlight),
      subMenu: "assistance",
      isToggle: true,
      checked: props.showEdgeHighlight,
    },
    {
      id: "clusterOutline",
      section: "settings",
      visible: !!props.onToggleClusterOutline,
      label: "Cluster Outlines",
      sortKey: "Cluster Outlines",
      title: "Show outlines around completed clusters",
      ariaLabel: props.showClusterOutline
        ? "Cluster outlines on"
        : "Cluster outlines off",
      onClick: c(props.onToggleClusterOutline ?? (() => {})),
      subMenu: "assistance",
      isToggle: true,
      checked: !!props.showClusterOutline,
    },
    {
      id: "ghostHint",
      section: "settings",
      visible: false,
      label: "Ghost Hint",
      sortKey: "Ghost Hint",
      title: "Show ghost placement when dragging a piece",
      onClick: c(props.onToggleGhostHint),
      subMenu: "assistance",
      isToggle: true,
      checked: props.showGhostHint,
    },
    {
      id: "ghostWhenIdle",
      section: "settings",
      visible: false,
      label: "Ghost When Idle",
      sortKey: "Ghost When Idle",
      title: "Show ghost after a moment of idleness",
      onClick: c(props.onToggleGhostWhenIdle),
      subMenu: "assistance",
      isToggle: true,
      checked: props.showGhostWhenIdle,
    },
    {
      id: "immersiveMode",
      section: "settings",
      visible: true,
      label: "Immersive Mode",
      sortKey: "Immersive Mode",
      title: "Hide UI until you hover or tap the edge",
      onClick: c(props.onToggleImmersiveMode),
      subMenu: "display",
      isToggle: true,
      checked: props.immersiveMode,
    },
    {
      id: "progressiveReveal",
      section: "settings",
      visible: true,
      label: "Progressive Reveal",
      sortKey: "Progressive Reveal",
      title: "Reveal reference image as you place pieces",
      onClick: c(props.onToggleProgressiveReveal ?? (() => {})),
      subMenu: "gameplay",
      isToggle: true,
      checked: !!props.progressiveRevealMode,
    },
    {
      id: "unlockPiecesAlpha",
      section: "settings",
      visible: true,
      label: "Unlock Pieces",
      sortKey: "Unlock Pieces",
      title: "Allow moving snapped pieces again (experimental)",
      onClick: c(props.onTogglePieceLocking),
      subMenu: "gameplay",
      isToggle: true,
      checked: !props.pieceLockingEnabled,
      ariaLabel: props.pieceLockingEnabled ? "Unlock pieces off" : "Unlock pieces on",
    },
    {
      id: "pieceCutClassic",
      section: "settings",
      visible: !!props.onPieceCutTypeChange,
      label: "Classic",
      sortKey: "Classic",
      title: "Classic jigsaw cuts – applies to next puzzle",
      onClick: c(() => props.onPieceCutTypeChange?.("classic")),
      subMenu: "pieceShape",
      radioSelected: (props.pieceCutType ?? "classic") === "classic",
      ariaLabel: "Classic – applies to next puzzle",
    },
    {
      id: "pieceCutIrregular",
      section: "settings",
      visible: !!props.onPieceCutTypeChange,
      label: "Irregular",
      sortKey: "Irregular",
      title: "Irregular wavy cuts – applies to next puzzle",
      onClick: c(() => props.onPieceCutTypeChange?.("irregular")),
      subMenu: "pieceShape",
      radioSelected: (props.pieceCutType ?? "classic") === "irregular",
      ariaLabel: "Irregular – applies to next puzzle",
    },
    {
      id: "pieceCutHard",
      section: "settings",
      visible: !!props.onPieceCutTypeChange,
      label: "Hard",
      sortKey: "Hard",
      title: "Hard uniform cuts – applies to next puzzle",
      onClick: c(() => props.onPieceCutTypeChange?.("hard")),
      subMenu: "pieceShape",
      radioSelected: (props.pieceCutType ?? "classic") === "hard",
      ariaLabel: "Hard – applies to next puzzle",
    },
  ];
}
