/**
 * Header menu items: Audio, Advanced, Stats, Share, Contribute, Help.
 */
import type {
  HeaderMenuProps,
  MenuItemConfig,
} from "@/screens/Play/components/headerMenu/headerMenuConfigTypes";

const GITHUB_REPO_URL = "https://github.com/NickTheDevOpsGuy/phuzzle";
const GITHUB_CONTRIBUTORS_URL =
  "https://github.com/NickTheDevOpsGuy/phuzzle/blob/develop/CONTRIBUTORS.md";

export function getRestItems(
  props: HeaderMenuProps,
  c: (fn: () => void) => () => void,
  navigate: (path: string) => void,
): MenuItemConfig[] {
  return [
    {
      id: "haptics",
      section: "settings",
      visible: props.canShowHaptics,
      label: "Haptics",
      sortKey: "Haptics",
      title: "Vibration feedback on snap and actions",
      onClick: c(props.onToggleHaptics),
      subMenu: "audio",
      isToggle: true,
      checked: props.hapticsEnabled,
    },
    {
      id: "sound",
      section: "settings",
      visible: true,
      label: "Sound Effects",
      sortKey: "Sound Effects",
      title: "Play sounds when placing and snapping pieces",
      onClick: c(props.onToggleSound),
      subMenu: "audio",
      isToggle: true,
      checked: props.soundEnabled,
    },
    {
      id: "music",
      section: "settings",
      visible: !!props.onToggleMusic,
      label: "Background Music",
      sortKey: "Background Music",
      title: "Theme-based ambient music",
      ariaLabel: props.musicEnabled ? "Background music on" : "Background music off",
      onClick: c(props.onToggleMusic ?? (() => {})),
      subMenu: "audio",
      isToggle: true,
      checked: !!props.musicEnabled,
    },
    {
      id: "clearCache",
      section: "settings",
      visible: !!props.onClearCache,
      label: "Clear Cache",
      sortKey: "Clear Cache",
      title: "Clear cached puzzle images and data",
      onClick: c(props.onClearCache ?? (() => {})),
      subMenu: "advanced",
    },
    {
      id: "perfOverlay",
      section: "settings",
      visible: props.canShowDebug,
      label: "Performance Overlay",
      sortKey: "Performance Overlay",
      title: "Show FPS and draw call stats",
      onClick: c(props.onTogglePerfOverlay),
      subMenu: "advanced",
      isToggle: true,
      checked: props.debug.showPerfOverlay,
    },
    {
      id: "showSilhouette",
      section: "settings",
      visible: props.canShowDebug && !!props.onToggleShowSilhouette,
      label: "Silhouette debug",
      sortKey: "Silhouette debug",
      title:
        "Render pieces as solid color + black outline only (confirms shapes, no seams)",
      onClick: c(props.onToggleShowSilhouette ?? (() => {})),
      subMenu: "advanced",
      isToggle: true,
      checked: !!props.debug.showSilhouette,
    },
    {
      id: "resetStats",
      section: "settings",
      visible: !!props.onResetStats,
      label: "Reset Local Stats",
      sortKey: "Reset Local Stats",
      title: "Clear all local best times – cannot be undone",
      onClick: c(props.onResetStats ?? (() => {})),
      subMenu: "advanced",
    },
    {
      id: "stats",
      section: "settings",
      visible: true,
      label: "Leaderboard",
      sortKey: "Leaderboard",
      title: "View daily and best-time leaderboards",
      onClick: c(() => navigate("/stats")),
      subMenu: "stats",
    },
    {
      id: "share",
      section: "settings",
      visible: !!props.onSharePuzzle,
      label: "Co-op",
      sortKey: "Co-op",
      title: "Start a co-op session to solve together",
      disabled: props.shareDisabled,
      disabledTitle: props.shareDisabled ? "Creating session…" : undefined,
      onClick: c(props.onSharePuzzle ?? (() => {})),
      subMenu: "share",
    },
    {
      id: "repo",
      section: "contribute",
      visible: true,
      label: "Get Involved",
      sortKey: "Get Involved",
      title: "Contribute on GitHub",
      onClick: c(() => window.open(GITHUB_REPO_URL, "_blank", "noopener,noreferrer")),
      subMenu: "contribute",
    },
    {
      id: "contributors",
      section: "contribute",
      visible: true,
      label: "Meet the Team",
      sortKey: "Meet the Team",
      title: "View contributors",
      onClick: c(() =>
        window.open(GITHUB_CONTRIBUTORS_URL, "_blank", "noopener,noreferrer"),
      ),
      subMenu: "contribute",
    },
    {
      id: "howToPlay",
      section: "help",
      visible: true,
      label: "How to Play",
      sortKey: "How to Play",
      title: "Learn the basics",
      onClick: c(props.onShowHowToPlay),
      subMenu: "help",
    },
    {
      id: "shortcuts",
      section: "help",
      visible: true,
      label: "Keyboard & Controls",
      sortKey: "Keyboard & Controls",
      title: "View keyboard shortcuts",
      onClick: c(props.onShowShortcuts),
      subMenu: "help",
    },
  ];
}
