import type {
  HeaderMenuProps,
  MenuItemConfig,
} from "@/screens/Play/components/headerMenu/headerMenuConfigTypes";

export function getModeItems(
  props: HeaderMenuProps,
  c: (fn: () => void) => () => void,
  showTimer: boolean,
): MenuItemConfig[] {
  return [
    {
      id: "deliberateDetach",
      section: "settings",
      visible: !!props.onToggleDeliberateDetach,
      label: "Deliberate Detach",
      sortKey: "Deliberate Detach",
      title: "Require hold or shake to detach placed pieces",
      ariaLabel: props.deliberateDetachEnabled
        ? "Deliberate detach on"
        : "Deliberate detach off",
      onClick: c(props.onToggleDeliberateDetach ?? (() => {})),
      subMenu: "modes",
      isToggle: true,
      checked: !!props.deliberateDetachEnabled,
    },
    {
      id: "autoRotateOnSnap",
      section: "settings",
      visible: true,
      label: "Auto-align on snap",
      sortKey: "Auto-align on snap",
      title:
        "When on, pieces snap to correct rotation when placed next to another. When off, you must rotate them yourself.",
      onClick: c(props.onToggleAutoRotateOnSnap ?? (() => {})),
      subMenu: "modes",
      isToggle: true,
      checked: props.autoRotateOnSnap !== false,
    },
    {
      id: "magneticSnap",
      section: "settings",
      visible: !!props.onToggleMagneticSnap,
      label: "Magnetic Snap",
      sortKey: "Magnetic Snap",
      title: "Gently pulls nearby pieces into alignment before snap",
      onClick: c(props.onToggleMagneticSnap ?? (() => {})),
      subMenu: "gameplay",
      isToggle: true,
      checked: props.magneticSnapEnabled !== false,
    },
    {
      id: "snapGlow",
      section: "settings",
      visible: false,
      label: "Snap Glow",
      sortKey: "Snap Glow",
      title: "Highlights pieces as they approach a valid snap position",
      onClick: c(props.onToggleSnapGlow ?? (() => {})),
      subMenu: "gameplay",
      isToggle: true,
      checked: props.snapGlowEnabled !== false,
    },
    {
      id: "relaxedMode",
      section: "settings",
      visible: !!props.onToggleRelaxedMode,
      label: "Relaxed Mode",
      sortKey: "Relaxed Mode",
      title: "Hide timer and take your time",
      ariaLabel: props.relaxedModeEnabled ? "Relaxed Mode on" : "Relaxed Mode off",
      onClick: c(props.onToggleRelaxedMode ?? (() => {})),
      subMenu: "modes",
      isToggle: true,
      checked: !!props.relaxedModeEnabled,
    },
    {
      id: "driftMode",
      section: "settings",
      visible: !!props.onToggleDriftMode,
      label: "Drift Mode",
      sortKey: "Drift Mode",
      title: "Pieces drift slightly for organic feel",
      ariaLabel: props.driftModeEnabled ? "Drift Mode on" : "Drift Mode off",
      onClick: c(props.onToggleDriftMode ?? (() => {})),
      subMenu: "modes",
      isToggle: true,
      checked: !!props.driftModeEnabled,
    },
    {
      id: "showTimer",
      section: "settings",
      visible: true,
      label: "Show Timer",
      sortKey: "Show Timer",
      title: "Show or hide timer",
      onClick: c(() => props.setTimeMode(showTimer ? "relaxed" : "active")),
      subMenu: "modes",
      isToggle: true,
      checked: showTimer,
    },
    {
      id: "zenMode",
      section: "settings",
      visible: true,
      label: "Zen Ambient",
      sortKey: "Zen Ambient",
      title: "No timer or rankings; subtle ambient background and soft transitions",
      onClick: c(props.onToggleZenMode ?? (() => {})),
      subMenu: "modes",
      isToggle: true,
      checked: !!props.zenModeEnabled,
    },
    {
      id: "mysteryMode",
      section: "settings",
      visible: true,
      label: "Mystery Mode",
      sortKey: "Mystery Mode",
      title: "Hide reference image; reveal sections only after correct placements",
      onClick: c(props.onToggleMysteryMode ?? (() => {})),
      subMenu: "modes",
      isToggle: true,
      checked: !!props.mysteryModeEnabled,
    },
    {
      id: "precisionMode",
      section: "settings",
      visible: true,
      label: "Precision Mode",
      sortKey: "Precision Mode",
      title: "Score snap accuracy; higher precision earns bonus ranking points",
      onClick: c(props.onTogglePrecisionMode ?? (() => {})),
      subMenu: "modes",
      isToggle: true,
      checked: !!props.precisionModeEnabled,
    },
    {
      id: "dynamicDifficulty",
      section: "settings",
      visible: true,
      label: "Dynamic Difficulty",
      sortKey: "Dynamic Difficulty",
      title: "Puzzle adapts tolerance and complexity from your skill history",
      onClick: c(props.onToggleDynamicDifficulty ?? (() => {})),
      subMenu: "modes",
      isToggle: true,
      checked: !!props.dynamicDifficultyEnabled,
    },
    {
      id: "adaptivePersonality",
      section: "settings",
      visible: true,
      label: "Adaptive Personality",
      sortKey: "Adaptive Personality",
      title: "UI tone adapts to your pace (fast = competitive, slow = calm)",
      onClick: c(props.onToggleAdaptivePersonality ?? (() => {})),
      subMenu: "modes",
      isToggle: true,
      checked: !!props.adaptivePersonalityEnabled,
    },
  ];
}
