import type { MutableRefObject } from "react";
import type { PuzzleManager } from "@/puzzle/manager/PuzzleManager";
import type { PuzzleState } from "@/puzzle/core/types";
import type { Theme } from "@/hooks/useTheme";
import type { DailyVisualModifier } from "@/daily/dailyPuzzleCore";
import type { DebugFlags } from "@/screens/Play/components/headerMenu/headerMenuConfigTypes";
import type { UndoSnapBackFrom } from "@/screens/Play/core/utils/playUtils";
import type { TimeMode } from "@/screens/Play/core/time/timeMode";

export type ViewportHandle = {
  reset: () => void;
  zoomIn: () => void;
  zoomOut: () => void;
};

export type BuildHeaderMenuPropsArgs = {
  theme: Theme;
  setTheme: (t: Theme) => void;
  timeMode: TimeMode;
  setTimeMode: (m: TimeMode | ((prev: TimeMode) => TimeMode)) => void;
  countdownMinutes: number;
  setCountdownMinutes: (n: number | ((prev: number) => number)) => void;
  showPreview: boolean;
  soundEnabled: boolean;
  musicEnabled: boolean;
  hapticsEnabled: boolean;
  pieceLockingEnabled: boolean;
  setPieceLockingEnabled: (fn: (p: boolean) => boolean) => void;
  magneticSnapEnabled: boolean;
  setMagneticSnapEnabled: (fn: (m: boolean) => boolean) => void;
  snapGlowEnabled: boolean;
  setSnapGlowEnabled: (fn: (g: boolean) => boolean) => void;
  autoRotateOnSnap: boolean;
  setAutoRotateOnSnap: (fn: (a: boolean) => boolean) => void;
  showGhostHint: boolean;
  setShowGhostHint: (fn: (g: boolean) => boolean) => void;
  showGhostWhenIdle: boolean;
  showEdgeHighlight: boolean;
  showClusterOutline: boolean;
  onToggleClusterOutline: () => void;
  deliberateDetachEnabled: boolean;
  onToggleDeliberateDetach: () => void;
  showAlignmentGrid: boolean;
  setShowAlignmentGrid: (fn: (a: boolean) => boolean) => void;
  isFullscreen: boolean;
  isCoarsePointer: boolean;
  showDebug: boolean;
  debug: DebugFlags;
  setShowNewGameModal: (v: boolean) => void;
  onStartThisPuzzleOver?: () => void;
  isComplete?: boolean;
  manager: PuzzleManager | null;
  isPaused: boolean;
  state: PuzzleState | null;
  setState: (s: PuzzleState) => void;
  playUndo: (s: "undo") => void;
  undoCountRef: MutableRefObject<number>;
  undoSnapBackRef: MutableRefObject<{
    fromPositions: UndoSnapBackFrom;
    startMs: number;
  } | null>;
  viewport: ViewportHandle;
  relaxedModeEnabled: boolean;
  toggleRelaxedMode: () => void;
  driftModeEnabled: boolean;
  toggleDriftMode: () => void;
  toggleShowGhostWhenIdle: () => void;
  toggleShowEdgeHighlight: () => void;
  setShowShortcuts: (v: boolean) => void;
  setShowHowToPlay: (v: boolean) => void;
  toggleDebug: () => void;
  togglePerfOverlay: () => void;
  toggleShowSilhouette: () => void;
  immersiveMode: boolean;
  handleToggleImmersiveMode: () => void;
  progressiveRevealMode: boolean;
  setProgressiveRevealMode: (fn: (v: boolean) => boolean) => void;
  pieceCutType: "classic" | "irregular" | "hard";
  setPieceCutType: (cut: "classic" | "irregular" | "hard") => void;
  handleSharePuzzle: (() => void | Promise<void>) | undefined;
  creatingSession: boolean;
  setShowThemeModal: (v: boolean) => void;
  dailyPreferredModifier: DailyVisualModifier | undefined;
  setDailyPreferredModifier: (m: DailyVisualModifier) => void;
  setShowResetStatsConfirm: (v: boolean) => void;
  setShowClearCacheConfirm: (v: boolean) => void;
  snapToleranceOverride: number;
  setSnapToleranceOverride: (value: number) => void;
  zenModeEnabled: boolean;
  mysteryModeEnabled: boolean;
  precisionModeEnabled: boolean;
  dynamicDifficultyEnabled: boolean;
  adaptivePersonalityEnabled: boolean;
  toggleZenMode: () => void;
  toggleMysteryMode: () => void;
  togglePrecisionMode: () => void;
  toggleDynamicDifficulty: () => void;
  toggleAdaptivePersonality: () => void;
  minimapVisible: boolean;
  toggleMinimap: () => void;
  undoRedoEnabled: boolean;
  onToggleUndoRedo: () => void;
  setShowPreview: (fn: (p: boolean) => boolean) => void;
  toggleSound: () => void;
  toggleMusic: () => void;
  toggleHaptics: () => void;
  toggleFullscreen: () => void;
  colorblindFriendly: boolean;
  onToggleColorBlindFriendly: () => void;
};

export type BuildHudPropsArgs = {
  state: PuzzleState | null;
  elapsedSeconds: number;
  moveCount: number;
  adaptivePersonalityEnabled: boolean;
  piecesLeft: number;
  totalPieces: number;
  isPaused: boolean;
  isComplete: boolean;
  timeMode: TimeMode;
  countdownMinutes: number;
  bestTimeSeconds: number | null;
  quadrantTimes: Record<0 | 1 | 2 | 3, number | null>;
  grid: { rows: number; cols: number } | null;
  lives: number;
  setIsPaused: (fn: (p: boolean) => boolean) => void;
  zenModeEnabled: boolean;
};

export type BuildTopBarButtonsPropsArgs = {
  showPreview: boolean;
  soundEnabled: boolean;
  isFullscreen: boolean;
  showDebug: boolean;
  isCoarsePointer: boolean;
  setShowPreview: (fn: (p: boolean) => boolean) => void;
  toggleSound: () => void;
  toggleFullscreen: () => void;
  setShowShortcuts: (v: boolean) => void;
  toggleDebug: () => void;
  setShowNewGameModal: (v: boolean) => void;
};
