/**
 * Builds headerMenuProps, hudProps, and topBarButtonsProps for PlayScreenTopBar.
 * Extracted from PlayScreen to keep the main component smaller.
 */
import type { HeaderMenuProps } from "@/screens/Play/components/headerMenu/headerMenuConfigTypes";
import { buildHeaderMenuProps } from "@/screens/Play/hooks/topBar/usePlayScreenTopBarPropsBuilders";
import {
  buildHudProps,
  buildTopBarButtonsProps,
} from "@/screens/Play/hooks/topBar/usePlayScreenTopBarHudBuilders";
import type {
  PlayScreenTopBarPropsResult,
  UsePlayScreenTopBarPropsParams,
} from "@/screens/Play/hooks/topBar/usePlayScreenTopBarProps.types";

export function usePlayScreenTopBarProps(
  params: UsePlayScreenTopBarPropsParams,
): PlayScreenTopBarPropsResult {
  const {
    theme,
    setTheme,
    timeMode,
    setTimeMode,
    countdownMinutes,
    setCountdownMinutes,
    showPreview,
    setShowPreview,
    soundEnabled,
    musicEnabled,
    hapticsEnabled,
    pieceLockingEnabled,
    setPieceLockingEnabled,
    magneticSnapEnabled,
    setMagneticSnapEnabled,
    snapGlowEnabled,
    setSnapGlowEnabled,
    showGhostHint,
    setShowGhostHint,
    showGhostWhenIdle,
    showEdgeHighlight,
    showClusterOutline,
    deliberateDetachEnabled,
    showAlignmentGrid,
    setShowAlignmentGrid,
    toggleRelaxedMode,
    toggleDriftMode,
    toggleShowClusterOutline,
    toggleDeliberateDetach,
    toggleShowGhostWhenIdle,
    toggleShowEdgeHighlight,
    toggleSound,
    toggleMusic,
    toggleHaptics,
    toggleFullscreen,
    toggleDebug,
    togglePerfOverlay,
    isFullscreen,
    isCoarsePointer,
    showDebug,
    debug,
    setShowNewGameModal,
    onStartThisPuzzleOver,
    setShowShortcuts,
    setShowHowToPlay,
    setShowThemeModal,
    setShowResetStatsConfirm,
    setShowClearCacheConfirm,
    manager,
    state,
    setState,
    isPaused,
    setIsPaused,
    playUndo,
    undoCountRef,
    undoSnapBackRef,
    viewport,
    relaxedModeEnabled,
    driftModeEnabled,
    immersiveMode,
    handleToggleImmersiveMode,
    progressiveRevealMode,
    setProgressiveRevealMode,
    pieceCutType,
    setPieceCutType,
    handleSharePuzzle,
    creatingSession,
    dailyPreferredModifier,
    setDailyPreferredModifier,
    snapToleranceOverride,
    setSnapToleranceOverride,
    elapsedSeconds,
    piecesLeft,
    totalPieces,
    isComplete,
    grid,
    quadrantTimes,
    bestTimeSeconds,
    lives,
    sessionId,
    realtimeStatus,
    connectedCount,
    showImmersiveUi,
    scheduleImmersiveHide,
    zenModeEnabled,
    mysteryModeEnabled,
    precisionModeEnabled,
    dynamicDifficultyEnabled,
    adaptivePersonalityEnabled,
    toggleZenMode,
    toggleMysteryMode,
    togglePrecisionMode,
    toggleDynamicDifficulty,
    toggleAdaptivePersonality,
    minimapVisible,
    toggleMinimap,
    autoRotateOnSnap,
    setAutoRotateOnSnap,
  } = params;

  const headerMenuProps: HeaderMenuProps = buildHeaderMenuProps({
    theme,
    setTheme,
    timeMode,
    setTimeMode,
    countdownMinutes,
    setCountdownMinutes,
    showPreview,
    soundEnabled,
    musicEnabled,
    hapticsEnabled,
    pieceLockingEnabled,
    setPieceLockingEnabled,
    magneticSnapEnabled,
    setMagneticSnapEnabled,
    snapGlowEnabled,
    setSnapGlowEnabled,
    autoRotateOnSnap,
    setAutoRotateOnSnap,
    showGhostHint,
    setShowGhostHint,
    showGhostWhenIdle,
    showEdgeHighlight,
    showClusterOutline,
    onToggleClusterOutline: toggleShowClusterOutline,
    deliberateDetachEnabled,
    onToggleDeliberateDetach: toggleDeliberateDetach,
    showAlignmentGrid,
    setShowAlignmentGrid,
    isFullscreen,
    isCoarsePointer,
    showDebug,
    debug,
    setShowNewGameModal,
    onStartThisPuzzleOver,
    isComplete,
    manager,
    isPaused,
    state,
    setState,
    playUndo,
    undoCountRef,
    undoSnapBackRef,
    viewport,
    relaxedModeEnabled,
    toggleRelaxedMode,
    driftModeEnabled,
    toggleDriftMode,
    toggleShowGhostWhenIdle,
    toggleShowEdgeHighlight,
    setShowShortcuts,
    setShowHowToPlay,
    toggleDebug,
    togglePerfOverlay,
    immersiveMode,
    handleToggleImmersiveMode,
    progressiveRevealMode,
    setProgressiveRevealMode,
    pieceCutType,
    setPieceCutType,
    handleSharePuzzle,
    creatingSession,
    setShowThemeModal,
    dailyPreferredModifier,
    setDailyPreferredModifier,
    setShowResetStatsConfirm,
    setShowClearCacheConfirm,
    snapToleranceOverride,
    setSnapToleranceOverride,
    zenModeEnabled,
    mysteryModeEnabled,
    precisionModeEnabled,
    dynamicDifficultyEnabled,
    adaptivePersonalityEnabled,
    toggleZenMode,
    toggleMysteryMode,
    togglePrecisionMode,
    toggleDynamicDifficulty,
    toggleAdaptivePersonality,
    minimapVisible,
    toggleMinimap,
    setShowPreview,
    toggleSound,
    toggleMusic,
    toggleHaptics,
    toggleFullscreen,
  });

  const hudProps = buildHudProps({
    state,
    elapsedSeconds,
    adaptivePersonalityEnabled,
    piecesLeft,
    totalPieces,
    isPaused,
    isComplete,
    timeMode,
    countdownMinutes,
    bestTimeSeconds,
    quadrantTimes,
    grid,
    lives,
    setIsPaused,
    zenModeEnabled,
  });

  const topBarButtonsProps = buildTopBarButtonsProps({
    showPreview,
    soundEnabled,
    isFullscreen,
    showDebug,
    isCoarsePointer,
    setShowPreview,
    toggleSound,
    toggleFullscreen,
    setShowShortcuts,
    toggleDebug,
    setShowNewGameModal,
  });

  return {
    headerMenuProps,
    hudProps,
    topBarButtonsProps,
    sessionId,
    realtimeStatus,
    connectedCount,
    showHud: !isComplete && !isPaused,
    immersiveMode,
    showImmersiveUi,
    onPointerLeave: immersiveMode ? scheduleImmersiveHide : undefined,
  };
}
