import type { MutableRefObject } from "react";
import type { PuzzleManager } from "@/puzzle/manager/PuzzleManager";
import type { PuzzleState } from "@/puzzle/core/types";
import type {
  HeaderMenuProps,
  DebugFlags,
} from "@/screens/Play/components/headerMenu/headerMenuConfigTypes";
import type { TimeMode } from "@/screens/Play/core/time/timeMode";
import type { Theme } from "@/hooks/useTheme";
import type { RealtimeStatus } from "@/screens/Play/hooks/gameplay/usePuzzleSession";
import type { ViewportHandle } from "@/screens/Play/hooks/topBar/usePlayScreenTopBarPropsBuilders.types";

export type UsePlayScreenTopBarPropsParams = {
  theme: Theme;
  setTheme: (t: Theme) => void;
  timeMode: TimeMode;
  setTimeMode: (m: TimeMode | ((prev: TimeMode) => TimeMode)) => void;
  countdownMinutes: number;
  setCountdownMinutes: (n: number | ((prev: number) => number)) => void;
  showPreview: boolean;
  setShowPreview: (fn: (p: boolean) => boolean) => void;
  soundEnabled: boolean;
  musicEnabled: boolean;
  hapticsEnabled: boolean;
  pieceLockingEnabled: boolean;
  setPieceLockingEnabled: (fn: (p: boolean) => boolean) => void;
  magneticSnapEnabled: boolean;
  setMagneticSnapEnabled: (fn: (m: boolean) => boolean) => void;
  snapGlowEnabled: boolean;
  setSnapGlowEnabled: (fn: (g: boolean) => boolean) => void;
  autoRotateOnSnap: boolean;
  setAutoRotateOnSnap: (fn: (a: boolean) => boolean) => void;
  showGhostHint: boolean;
  setShowGhostHint: (fn: (g: boolean) => boolean) => void;
  showGhostWhenIdle: boolean;
  showEdgeHighlight: boolean;
  showClusterOutline: boolean;
  deliberateDetachEnabled: boolean;
  showAlignmentGrid: boolean;
  setShowAlignmentGrid: (fn: (a: boolean) => boolean) => void;
  toggleRelaxedMode: () => void;
  toggleDriftMode: () => void;
  toggleShowClusterOutline: () => void;
  toggleDeliberateDetach: () => void;
  toggleShowGhostWhenIdle: () => void;
  toggleShowEdgeHighlight: () => void;
  toggleSound: () => void;
  toggleMusic: () => void;
  toggleHaptics: () => void;
  toggleFullscreen: () => void;
  toggleDebug: () => void;
  togglePerfOverlay: () => void;
  toggleShowSilhouette: () => void;
  isFullscreen: boolean;
  isCoarsePointer: boolean;
  showDebug: boolean;
  debug: DebugFlags;
  setShowNewGameModal: (v: boolean) => void;
  onStartThisPuzzleOver?: () => void;
  setShowShortcuts: (v: boolean) => void;
  setShowHowToPlay: (v: boolean) => void;
  setShowThemeModal: (v: boolean) => void;
  setShowResetStatsConfirm: (v: boolean) => void;
  setShowClearCacheConfirm: (v: boolean) => void;
  manager: PuzzleManager | null;
  state: PuzzleState | null;
  setState: (s: PuzzleState) => void;
  isPaused: boolean;
  setIsPaused: (fn: (p: boolean) => boolean) => void;
  playUndo: (s: "undo") => void;
  undoCountRef: MutableRefObject<number>;
  undoSnapBackRef: MutableRefObject<{
    fromPositions: import("@/screens/Play/core/utils/playUtils").UndoSnapBackFrom;
    startMs: number;
  } | null>;
  viewport: ViewportHandle;
  relaxedModeEnabled: boolean;
  driftModeEnabled: boolean;
  immersiveMode: boolean;
  handleToggleImmersiveMode: () => void;
  progressiveRevealMode: boolean;
  setProgressiveRevealMode: (fn: (v: boolean) => boolean) => void;
  pieceCutType: "classic" | "irregular" | "hard";
  setPieceCutType: (cut: "classic" | "irregular" | "hard") => void;
  handleSharePuzzle: (() => void | Promise<void>) | undefined;
  creatingSession: boolean;
  dailyPreferredModifier:
    | import("@/daily/dailyPuzzleCore").DailyVisualModifier
    | undefined;
  setDailyPreferredModifier: (
    m: import("@/daily/dailyPuzzleCore").DailyVisualModifier,
  ) => void;
  snapToleranceOverride: number;
  setSnapToleranceOverride: (value: number) => void;
  elapsedSeconds: number;
  moveCount: number;
  piecesLeft: number;
  totalPieces: number;
  isComplete: boolean;
  /** Win celebration modal is visible — hide HUD with tray/board chrome, not on the last-snap delay. */
  winCelebrationModalVisible: boolean;
  grid: { rows: number; cols: number } | null;
  quadrantTimes: Record<0 | 1 | 2 | 3, number | null>;
  bestTimeSeconds: number | null;
  lives: number;
  sessionId: string | null;
  realtimeStatus: RealtimeStatus;
  connectedCount: number;
  showImmersiveUi: boolean;
  scheduleImmersiveHide: () => void;
  zenModeEnabled: boolean;
  mysteryModeEnabled: boolean;
  precisionModeEnabled: boolean;
  dynamicDifficultyEnabled: boolean;
  adaptivePersonalityEnabled: boolean;
  toggleZenMode: () => void;
  toggleMysteryMode: () => void;
  togglePrecisionMode: () => void;
  toggleDynamicDifficulty: () => void;
  toggleAdaptivePersonality: () => void;
  minimapVisible: boolean;
  toggleMinimap: () => void;
  undoRedoEnabled: boolean;
  onToggleUndoRedo: () => void;
};

export type PlayScreenTopBarPropsResult = {
  headerMenuProps: HeaderMenuProps;
  hudProps: {
    elapsedSeconds: number;
    moveCount: number;
    piecesLeft: number;
    totalPieces: number;
    isPaused: boolean;
    isComplete: boolean;
    timeMode: TimeMode;
    countdownMinutes?: number;
    bestTimeSeconds?: number | null;
    quadrantTimes?: Record<0 | 1 | 2 | 3, number | null>;
    quadrantPbs?: Record<0 | 1 | 2 | 3, number | null>;
    lives?: number;
    onTogglePause: () => void;
    uiTone?: "competitive" | "calm";
  };
  topBarButtonsProps: {
    showPreview: boolean;
    soundEnabled: boolean;
    isFullscreen: boolean;
    showDebug: boolean;
    isCoarsePointer: boolean;
    onTogglePreview: () => void;
    onToggleSound: () => void;
    onToggleFullscreen: () => void;
    onShowShortcuts: () => void;
    onToggleDebug: () => void;
    onNewPuzzle: () => void;
  };
  sessionId: string | null;
  realtimeStatus: RealtimeStatus;
  connectedCount: number;
  showHud: boolean;
  immersiveMode: boolean;
  showImmersiveUi: boolean;
  onPointerLeave: (() => void) | undefined;
};
