import { createUndoRedoHandler } from "@/screens/Play/core/utils/playUtils";
import type { HeaderMenuProps } from "@/screens/Play/components/headerMenu/headerMenuConfigTypes";
import type { BuildHeaderMenuPropsArgs } from "@/screens/Play/hooks/topBar/usePlayScreenTopBarPropsBuilders.types";
import { buildHeaderMenuToggleProps } from "@/screens/Play/hooks/topBar/usePlayScreenTopBarMenuToggles";

export function buildHeaderMenuProps(args: BuildHeaderMenuPropsArgs): HeaderMenuProps {
  const {
    theme,
    setTheme,
    timeMode,
    setTimeMode,
    countdownMinutes,
    setCountdownMinutes,
    showPreview,
    soundEnabled,
    musicEnabled,
    hapticsEnabled,
    pieceLockingEnabled,
    setPieceLockingEnabled,
    magneticSnapEnabled,
    setMagneticSnapEnabled,
    snapGlowEnabled,
    setSnapGlowEnabled,
    autoRotateOnSnap,
    setAutoRotateOnSnap,
    showGhostHint,
    setShowGhostHint,
    showGhostWhenIdle,
    showEdgeHighlight,
    showClusterOutline,
    onToggleClusterOutline,
    deliberateDetachEnabled,
    onToggleDeliberateDetach,
    showAlignmentGrid,
    setShowAlignmentGrid,
    isFullscreen,
    isCoarsePointer,
    showDebug,
    debug,
    setShowNewGameModal,
    onStartThisPuzzleOver,
    isComplete,
    manager,
    isPaused,
    state,
    setState,
    playUndo,
    undoCountRef,
    undoSnapBackRef,
    viewport,
    relaxedModeEnabled,
    toggleRelaxedMode,
    driftModeEnabled,
    toggleDriftMode,
    toggleShowGhostWhenIdle,
    toggleShowEdgeHighlight,
    setShowShortcuts,
    setShowHowToPlay,
    toggleDebug,
    togglePerfOverlay,
    toggleShowSilhouette,
    immersiveMode,
    handleToggleImmersiveMode,
    progressiveRevealMode,
    setProgressiveRevealMode,
    pieceCutType,
    setPieceCutType,
    handleSharePuzzle,
    creatingSession,
    setShowThemeModal,
    dailyPreferredModifier,
    setDailyPreferredModifier,
    setShowResetStatsConfirm,
    setShowClearCacheConfirm,
    snapToleranceOverride,
    setSnapToleranceOverride,
    zenModeEnabled,
    mysteryModeEnabled,
    precisionModeEnabled,
    dynamicDifficultyEnabled,
    adaptivePersonalityEnabled,
    toggleZenMode,
    toggleMysteryMode,
    togglePrecisionMode,
    toggleDynamicDifficulty,
    toggleAdaptivePersonality,
    minimapVisible,
    toggleMinimap,
    setShowPreview,
    toggleSound,
    toggleMusic,
    toggleHaptics,
    toggleFullscreen,
  } = args;

  return {
    title: "Phuzzle",
    theme,
    setTheme,
    timeMode,
    setTimeMode: (modeOrFn) => {
      if (hapticsEnabled && navigator.vibrate) navigator.vibrate(10);
      setTimeMode(modeOrFn);
    },
    countdownMinutes,
    setCountdownMinutes,
    showPreview,
    soundEnabled,
    musicEnabled,
    hapticsEnabled,
    pieceLockingEnabled,
    showGhostHint,
    showGhostWhenIdle,
    showEdgeHighlight,
    showClusterOutline,
    onToggleClusterOutline: () => {
      if (hapticsEnabled && typeof navigator?.vibrate === "function")
        navigator.vibrate(10);
      onToggleClusterOutline();
    },
    deliberateDetachEnabled,
    onToggleDeliberateDetach: () => {
      if (hapticsEnabled && typeof navigator?.vibrate === "function")
        navigator.vibrate(10);
      onToggleDeliberateDetach();
    },
    showAlignmentGrid,
    isFullscreen,
    canShowHaptics: isCoarsePointer && typeof navigator?.vibrate === "function",
    canShowFullscreen: typeof document !== "undefined" && !!document.fullscreenEnabled,
    canShowShortcuts: !isCoarsePointer,
    canShowDebug: showDebug,
    debug,
    onNewPuzzle: () => setShowNewGameModal(true),
    onStartThisPuzzleOver,
    isComplete,
    canUndo: !!(manager?.canUndo() && !isPaused && !state?.isComplete),
    onUndo: createUndoRedoHandler(
      manager ?? null,
      "undo",
      setState,
      () => Boolean(manager?.canUndo() && !isPaused && !state?.isComplete),
      playUndo,
      () => {
        undoCountRef.current += 1;
      },
      (fromPositions) => {
        undoSnapBackRef.current = { fromPositions, startMs: performance.now() };
      },
    ),
    canRedo: !!(manager?.canRedo() && !isPaused && !state?.isComplete),
    onRedo: createUndoRedoHandler(
      manager ?? null,
      "redo",
      setState,
      () => Boolean(manager?.canRedo() && !isPaused && !state?.isComplete),
      playUndo,
      undefined,
      (fromPositions) => {
        undoSnapBackRef.current = { fromPositions, startMs: performance.now() };
      },
    ),
    onResetView: () => viewport.reset(),
    ...buildHeaderMenuToggleProps({
      hapticsEnabled,
      setShowPreview,
      toggleSound,
      toggleMusic,
      toggleHaptics,
      setPieceLockingEnabled,
      magneticSnapEnabled,
      setMagneticSnapEnabled,
      snapGlowEnabled,
      setSnapGlowEnabled,
      autoRotateOnSnap,
      setAutoRotateOnSnap,
      relaxedModeEnabled,
      toggleRelaxedMode,
      driftModeEnabled,
      toggleDriftMode,
      setShowGhostHint,
      toggleShowGhostWhenIdle,
      toggleShowEdgeHighlight,
      setShowAlignmentGrid,
      toggleFullscreen,
      setShowShortcuts,
      setShowHowToPlay,
      toggleDebug,
      togglePerfOverlay,
      toggleShowSilhouette,
      immersiveMode,
      handleToggleImmersiveMode,
      setProgressiveRevealMode,
      pieceCutType,
      setPieceCutType,
      handleSharePuzzle,
      creatingSession,
      setShowThemeModal,
      dailyPreferredModifier,
      setDailyPreferredModifier,
      setShowResetStatsConfirm,
      setShowClearCacheConfirm,
      snapToleranceOverride,
      setSnapToleranceOverride,
      zenModeEnabled,
      mysteryModeEnabled,
      precisionModeEnabled,
      dynamicDifficultyEnabled,
      adaptivePersonalityEnabled,
      toggleZenMode,
      toggleMysteryMode,
      togglePrecisionMode,
      toggleDynamicDifficulty,
      toggleAdaptivePersonality,
      minimapVisible,
      toggleMinimap,
    }),
    onZoomIn: () => viewport.zoomIn(),
    onZoomOut: () => viewport.zoomOut(),
    progressiveRevealMode,
    colorblindFriendly: args.colorblindFriendly,
    onToggleColorBlindFriendly: args.onToggleColorBlindFriendly,
  };
}
