import { usePlayScreenTopBarProps } from "./hooks/usePlayScreenTopBarProps";
import { SHOW_DEBUG } from "./playScreenUtils";
import {
  buildCompletionProps,
  buildPlayScreenPageVisuals,
  buildReplayPortalProps,
  getCompletionImageFallback,
} from "./playScreenSceneOverlays";
import { createPlayScreenLayoutProps } from "./playScreenLayoutPropsBuilder";

// eslint-disable-next-line @typescript-eslint/no-explicit-any -- ctx shape is large and shared across layout/behavior/interactions
export function usePlayScreenLayout(ctx: any) {
  const { setup, behavior, interactions } = ctx;
  const { ui, scene, timeMode, setTimeMode, countdownMinutes, setCountdownMinutes, grid, isHost, sessionIdFromUrl, sessionLoading, session, joinError, retryJoin, navigate, sessionId, realtimeStatus, creatingSession, searchParams, showE2ECompletion, sessionResult, lastEventTimestamp, lastDbWriteMs, channelName } = setup;
  const { manager, state, setState, puzzleKey, boardRef, canvasRef, trayRef, mainRef, elapsedSeconds, snapCombo, announcerLine, imgRef } = behavior;
  const { displayElapsedSeconds, left, total, isComplete, dailyVisualModifier, fogStrength, immersive, bestTimeSeconds, trayPieces, dragPreview, dragPreviewPiece, handleUndo, handleRedo, handleSharePuzzle, handleDownloadImage, handleNewGame, puzzleShareUrl, share, handlePointerDown, handlePointerMove, handlePointerUp, handlePointerCancel, handleLostPointerCapture, handleContextMenu, isDraggingBoard, handleTrayPieceClick } = interactions;

  const topBarProps = usePlayScreenTopBarProps({
    theme: scene.theme,
    setTheme: scene.setTheme,
    timeMode,
    setTimeMode,
    countdownMinutes,
    setCountdownMinutes,
    showPreview: ui.showPreview,
    setShowPreview: ui.setShowPreview,
    soundEnabled: ui.soundEnabled,
    musicEnabled: ui.musicEnabled,
    hapticsEnabled: ui.hapticsEnabled,
    pieceLockingEnabled: ui.pieceLockingEnabled,
    setPieceLockingEnabled: ui.setPieceLockingEnabled,
    magneticSnapEnabled: ui.magneticSnapEnabled,
    setMagneticSnapEnabled: ui.setMagneticSnapEnabled,
    snapGlowEnabled: ui.snapGlowEnabled,
    setSnapGlowEnabled: ui.setSnapGlowEnabled,
    autoRotateOnSnap: ui.autoRotateOnSnap,
    setAutoRotateOnSnap: ui.setAutoRotateOnSnap,
    showGhostHint: ui.showGhostHint,
    setShowGhostHint: ui.setShowGhostHint,
    showGhostWhenIdle: ui.showGhostWhenIdle,
    showEdgeHighlight: ui.showEdgeHighlight,
    showClusterOutline: ui.showClusterOutline,
    deliberateDetachEnabled: ui.deliberateDetachEnabled,
    showAlignmentGrid: ui.showAlignmentGrid,
    setShowAlignmentGrid: ui.setShowAlignmentGrid,
    toggleRelaxedMode: ui.toggleRelaxedMode,
    toggleDriftMode: ui.toggleDriftMode,
    toggleShowClusterOutline: ui.toggleShowClusterOutline,
    toggleDeliberateDetach: ui.toggleDeliberateDetach,
    toggleShowGhostWhenIdle: ui.toggleShowGhostWhenIdle,
    toggleShowEdgeHighlight: ui.toggleShowEdgeHighlight,
    toggleSound: ui.toggleSound,
    toggleMusic: ui.toggleMusic,
    toggleHaptics: ui.toggleHaptics,
    toggleFullscreen: ui.toggleFullscreen,
    toggleDebug: ui.toggleDebug,
    togglePerfOverlay: ui.togglePerfOverlay,
    isFullscreen: ui.isFullscreen,
    isCoarsePointer: scene.isCoarsePointer,
    showDebug: SHOW_DEBUG,
    debug: ui.debug,
    setShowNewGameModal: ui.setShowNewGameModal,
    setShowShortcuts: ui.setShowShortcuts,
    setShowHowToPlay: ui.setShowHowToPlay,
    setShowThemeModal: ui.setShowThemeModal,
    setShowResetStatsConfirm: scene.setShowResetStatsConfirm,
    setShowClearCacheConfirm: scene.setShowClearCacheConfirm,
    manager,
    state,
    setState,
    isPaused: ui.isPaused,
    setIsPaused: ui.setIsPaused,
    playUndo: ctx.soundPlay,
    undoCountRef: scene.undoCountRef,
    undoSnapBackRef: interactions.undoSnapBackRef,
    viewport: scene.viewport,
    relaxedModeEnabled: ui.relaxedModeEnabled,
    driftModeEnabled: ui.driftModeEnabled,
    immersiveMode: ui.immersiveMode,
    handleToggleImmersiveMode: immersive.handleToggleImmersiveMode,
    progressiveRevealMode: ui.progressiveRevealMode,
    setProgressiveRevealMode: ui.setProgressiveRevealMode,
    pieceCutType: ui.pieceCutType,
    setPieceCutType: ui.setPieceCutType,
    handleSharePuzzle,
    creatingSession,
    dailyPreferredModifier: ui.dailyPreferredModifier,
    setDailyPreferredModifier: ui.setDailyPreferredModifier,
    snapToleranceOverride: ui.snapToleranceOverride,
    setSnapToleranceOverride: ui.setSnapToleranceOverride,
    elapsedSeconds: displayElapsedSeconds,
    piecesLeft: left,
    totalPieces: total,
    isComplete,
    grid,
    quadrantTimes: scene.quadrantTimes,
    bestTimeSeconds,
    lives: scene.lives,
    sessionId,
    realtimeStatus,
    connectedCount: sessionResult.connectedCount,
    showImmersiveUi: immersive.showImmersiveUi,
    scheduleImmersiveHide: immersive.scheduleImmersiveHide,
    zenModeEnabled: ui.zenModeEnabled,
    mysteryModeEnabled: ui.mysteryModeEnabled,
    precisionModeEnabled: ui.precisionModeEnabled,
    dynamicDifficultyEnabled: ui.dynamicDifficultyEnabled,
    adaptivePersonalityEnabled: ui.adaptivePersonalityEnabled,
    toggleZenMode: ui.toggleZenMode,
    toggleMysteryMode: ui.toggleMysteryMode,
    togglePrecisionMode: ui.togglePrecisionMode,
    toggleDynamicDifficulty: ui.toggleDynamicDifficulty,
    toggleAdaptivePersonality: ui.toggleAdaptivePersonality,
    minimapVisible: ui.minimapVisible,
    toggleMinimap: ui.toggleMinimap,
  });

  const { pageClassName, pageStyle } = buildPlayScreenPageVisuals({
    zenModeEnabled: ui.zenModeEnabled,
    dailyVisualModifier,
    fogStrength,
  });

  const completionProps = buildCompletionProps({
    isComplete,
    completionDismissed: scene.completionDismissed,
    showE2ECompletion,
    state,
    displayElapsedSeconds,
    completionImageUrl: scene.completionImageUrl,
    fallbackImageUrl: getCompletionImageFallback(),
    imageRefUrl: imgRef.current?.src,
    undoCount: scene.undoCountRef.current,
    moveCount: scene.moveCountRef.current,
    rotationCount: scene.rotationCountRef.current,
    maxGroupSize: scene.maxGroupSizeRef.current,
    dailyVisualModifier,
    pieceCutType: ui.pieceCutType,
    isNewBest:
      timeMode === "best" &&
      state?.grid != null &&
      (bestTimeSeconds == null || elapsedSeconds < bestTimeSeconds),
    puzzleShareUrl,
    share: {
      copied: share.copied,
      canNativeShare: share.canNativeShare,
      handleCopyResults: share.handleCopyResults,
      handleNativeShare: share.handleNativeShare,
      handleCopyChallenge: share.handleCopyChallenge,
      handleNativeChallengeShare: share.handleNativeChallengeShare,
    },
    onDownloadImage: handleDownloadImage,
    onClose: () => {
      scene.setCompletionDismissed(true);
      scene.setCompletionImageUrl(undefined);
      scene.viewport.reset();
    },
    usedHint: scene.usedHintRef.current,
    precisionModeEnabled: ui.precisionModeEnabled,
    precisionSnaps: scene.precisionSnapsRef.current,
    adaptivePersonalityEnabled: ui.adaptivePersonalityEnabled,
    canReplay: behavior.replay.canReplay,
    onReplayClick: () => {
      behavior.replay.startReplay();
      scene.setCompletionDismissed(true);
      scene.setReplayBarOpen(true);
      scene.setCompletionImageUrl(undefined);
    },
    onNextPuzzle: handleNewGame,
  });

  const replayPortalProps = buildReplayPortalProps({
    replayBarOpen: scene.replayBarOpen,
    isReplayPaused: behavior.replay.isReplayPaused,
    onPlay: behavior.replay.resumeReplay,
    onPause: behavior.replay.pauseReplay,
    onRewind: behavior.replay.goToStart,
    onFastForward: behavior.replay.goToEnd,
    speed: behavior.replay.replaySpeed,
    onSpeedChange: behavior.replay.setReplaySpeed,
    currentIndex: behavior.replay.replayIndex,
    totalSnapshots: behavior.replay.snapshots.length,
    elapsedSeconds: behavior.replay.replayElapsedSeconds,
    totalSeconds:
      behavior.replay.snapshots.length > 0
        ? behavior.replay.snapshots[behavior.replay.snapshots.length - 1].elapsedSeconds
        : 0,
    onSeek: behavior.replay.seekToIndex,
    boardRect: scene.replayBarBoardRect ?? undefined,
    speedExplicitlyChosen: behavior.replay.speedExplicitlyChosen,
    onClose: () => {
      behavior.replay.stopReplay();
      scene.setReplayBarOpen(false);
      scene.setCompletionDismissed(false);
    },
  });

  return createPlayScreenLayoutProps({
    isHost,
    sessionIdFromUrl,
    sessionLoading,
    session,
    joinError,
    retryJoin,
    navigate,
    pageClassName,
    pageStyle,
    pageRef: ui.pageRef,
    immersiveMode: ui.immersiveMode,
    handleImmersiveReveal: immersive.handleImmersiveReveal,
    topBarProps,
    replayBarOpen: scene.replayBarOpen,
    showImmersiveUi: immersive.showImmersiveUi,
    awaitingResumeChoice: setup.managerResult.awaitingResumeChoice,
    resumeChoice: scene.resumeChoice,
    setResumeChoice: scene.setResumeChoice,
    showHelpChoice: ui.showHelpChoice,
    setShowHelpChoice: ui.setShowHelpChoice,
    setShowHowToPlay: ui.setShowHowToPlay,
    setShowShortcuts: ui.setShowShortcuts,
    showShortcuts: ui.showShortcuts,
    showThemeModal: ui.showThemeModal,
    setShowThemeModal: ui.setShowThemeModal,
    setShowFeedbackChoice: ui.setShowFeedbackChoice,
    hapticsEnabled: ui.hapticsEnabled,
    showNewGameModal: ui.showNewGameModal,
    setShowNewGameModal: ui.setShowNewGameModal,
    handleNewGame,
    showResetStatsConfirm: scene.showResetStatsConfirm,
    setShowResetStatsConfirm: scene.setShowResetStatsConfirm,
    showClearCacheConfirm: scene.showClearCacheConfirm,
    setShowClearCacheConfirm: scene.setShowClearCacheConfirm,
    showFeedbackChoice: ui.showFeedbackChoice,
    state,
    completionProps,
    replayPortalProps,
    mainRef,
    boardRef,
    canvasRef,
    puzzleKey,
    isComplete,
    isLoading: setup.managerResult.isLoading,
    elapsedSeconds,
    moveCount: scene.moveCountRef.current,
    snapCombo,
    minimapVisible: ui.minimapVisible,
    minimapSuppressed: scene.isCoarsePointer && isDraggingBoard,
    minimapPosition: ui.minimapPosition,
    boardSize: scene.boardSize,
    cycleMinimapPosition: ui.cycleMinimapPosition,
    viewport: scene.viewport,
    handlePointerDown,
    handlePointerMove,
    handlePointerUp,
    handlePointerCancel,
    handleLostPointerCapture,
    handleContextMenu,
    isPaused: ui.isPaused,
    setIsPaused: (next: boolean) => ui.setIsPaused(next),
    scheduleImmersiveHide: immersive.scheduleImmersiveHide,
    manager,
    trayRef,
    trayPieces,
    grid,
    handleTrayPieceClick,
    highlightedPieceIds: behavior.highlightedPieceIds,
    handleUndo,
    handleRedo,
    showPreview: ui.showPreview,
    mysteryModeEnabled: ui.mysteryModeEnabled,
    progressiveRevealMode: ui.progressiveRevealMode,
    imgRef,
    onPreviewTap: behavior.onPreviewTap,
    showTutorial: behavior.showTutorial,
    showHowToPlay: ui.showHowToPlay,
    dismissTutorial: behavior.dismissTutorial,
    dragPreviewPiece,
    dragPreview,
    onboarding: behavior.onboarding,
    showStreakToast: scene.showStreakToast,
    milestoneMessage: behavior.milestoneMessage,
    announcerLine,
    shareToast: scene.shareToast,
    searchParams,
    SHOW_DEBUG,
    debug: ui.debug,
    sessionId,
    sessionResultConnectedCount: sessionResult.connectedCount,
    lastEventTimestamp,
    lastDbWriteMs,
    channelName,
    perfStatsRef: scene.perfStatsRef,
  });
}
